on:
  workflow_call:
    inputs:
      renovate_log_level:
        description: Log level for renovateBot
        required: false
        type: string
        default: ""
    secrets:
      token:  # 👈 Accept token from calling workflow
        description: "GitHub Token"
        required: true
permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write
env:
  RENOVATE_VERSION: 38.98.0
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2
    - name: Run Renovate
      uses: renovatebot/github-action@v41.0.13
      env:
        RENOVATE_REPOSITORIES: "maheshkhade/renovatebot-demo"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LOG_LEVEL: info  # Enable detailed logs
        #RENOVATE_AUTODISCOVER: "true"
        #RENOVATE_TOKEN: ${{ secrets.RENOVATE_PAT }}
      with:
        #configurationFile: renovate.json
        token: ${{ secrets.token }}