on:
  workflow_call:
    inputs:
      renovate_log_level:
        description: Log level for renovateBot
        required: false
        type: string
        default: ""
permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write
env:
  RENOVATE_VERSION: 38.98.0
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2